### ISSUE TITLE
Travis build failing on macOS Sierra (10.12)

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/spinalcordtoolbox#2841]
https://travis-ci.org/github/neuropoly/spinalcordtoolbox/jobs/717990889

should we drop support?

**Comment by joshuacwnewton** [comment]
It looks like this is less about 10.12 and more about how we install `scikit-image`. 

For 10.13/10.14, [`scikit-image` provides a wheel to install](https://pypi.org/project/scikit-image/#files), but for 10.12 we have to install the sdist. For the sdist, it looks like we're running into a similar issue to https://github.com/scikit-learn/scikit-learn/issues/4164. 

The tl;dr is that `setup.py` in the `scikit-image` sdist requires `numpy` to be installed beforehand (i.e. a sequential install). But, `./install_sct` uses `pip install -r requirements.txt` for everything, so packages aren't installed sequentially.

I think this could be fixed by changing this line in our install script such that numpy is installed first.

https://github.com/neuropoly/spinalcordtoolbox/blob/b64cad3c846fd6bd7a557688b67b80fe0b2c6dc2/install_sct#L539

**Comment by jcohenadad** [comment]
> I think this could be fixed by changing this line in our install script such that numpy is installed first.

great! let's do it 👍

**Comment by joshuacwnewton** [comment]
Oops, looks like the same conclusion was arrived at for #2840. @kousu and @Drulex figured this out hours ago. :P

**Comment by kousu** [comment]
Getting rid of the explicit numpy was something I proposed (#2750). There was a good reason: installing numpy in requirements.txt and in install_sct made pip install numpy twice, slowing down installation (and possibly causing inconsistencies if we version one and forget to version the other); @Drulex did some snappy research and pointed us at this old thread https://github.com/scipy/scipy/issues/3379

> Not an issue we want to fix. At least until the ridiculous --upgrade behavior of setuptools is killed.
> ...
> The problem about declaring the dependency is that it very frequently involves a lengthy recompile and install of numpy when there is already an adequate numpy present (that setuptools does not accept for whatever reason).
> ...
> Yes. It's not that hard with only numpy as dependency, and certainly better than introducing issues for users due to pip/setuptools trying to upgrade numpy when that's not what they asked for.
> ...
> The problem really lies with the poor quality Python build/install tools

and their workaround code https://github.com/scipy/scipy/blob/834f756ebb4eb04049ed7bc26226a27fb58ca5ad/setup.py#L190 which I'm going to quote for posterity

```
    # Figure out whether to add ``*_requires = ['numpy']``.
    # We don't want to do that unconditionally, because we risk updating
    # an installed numpy which fails too often.  Just if it's not installed, we
    # may give it a try.  See gh-3379.
    build_requires = []
    try:
        import numpy
    except:
        build_requires = ['numpy>=1.5.1']
```

but that was 6 years ago. Surely there's a better solution now? Maybe not? ...maybe not, here's the latest: https://github.com/scipy/scipy/blob/2ed8169c5c4c9181cd38a52db614c692eb802c15/setup.py#L508-L521

```
    # Figure out whether to add ``*_requires = ['numpy']``.
    # We don't want to do that unconditionally, because we risk updating
    # an installed numpy which fails too often.  Just if it's not installed, we
    # may give it a try.  See gh-3379.
    try:
        import numpy
    except ImportError:  # We do not have numpy installed
        build_requires = ['numpy>=1.14.5']
    else:
        # If we're building a wheel, assume there already exist numpy wheels
        # for this platform, so it is safe to add numpy to build requirements.
        # See gh-5184.
        build_requires = (['numpy>=1.14.5'] if 'bdist_wheel' in sys.argv[1:]
                          else [])
```

I tried installing scipy from source (in a fresh venv):

```
(.venv36) [kousu@laptop scipy]$ python setup.py install

Note: if you need reliable uninstall behavior, then install
with pip instead of using `setup.py install`:

  - `pip install .`       (from a git repo or downloaded source
                           release)
  - `pip install scipy`   (last SciPy release on PyPI)


/home/kousu/src/neuropoly/.venv36/lib/python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
  File "setup.py", line 590, in <module>
    setup_package()
  File "setup.py", line 565, in setup_package
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy'
```

so it looks like their `build_requires` hack quoted above is just dead in the water. It's not working any more.

However, `pip` works:

```
(.venv36) [kousu@laptop scipy]$ pip install .
Processing /home/kousu/src/neuropoly/scipy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
```

this is because they're using the new pyproject.toml cruft:

```
$ cat pyproject.toml 
[build-system]
requires = [
    "wheel",
    "setuptools",
    "Cython>=0.29.18",
    "numpy==1.14.5; python_version=='3.6' and platform_system!='AIX'",
    "numpy==1.14.5; python_version=='3.7' and platform_system!='AIX'",
    "numpy==1.17.3; python_version>='3.8' and platform_system!='AIX'",
    "numpy==1.16.0; python_version=='3.6' and platform_system=='AIX'",
    "numpy==1.16.0; python_version=='3.7' and platform_system=='AIX'",
    "numpy==1.17.3; python_version>='3.8' and platform_system=='AIX'",
    "pybind11>=2.4.3",
]
```

--


Also, there's a comment in our requirements.txt that numpy is on top *on purpose* but it looks like at some point since then `pip` has changed and now installs...in alphabetical order? One of the comments that @Drulex found explicitly re-enables ordering (https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-243259447). So that workaround of ours isn't good anymore.

--

I think I can fix this. The problem is that scikit-image isn't using pyproject.toml, which is what modern pip requires. And this wasn't caught because they install build deps with `pip install -r`: 

https://github.com/scikit-image/scikit-image/blob/59fd9682aad41a1f69a35f05d2a7e15ebdfb8b29/tools/travis/before_install.sh#L78

So I think this is a bug in scikit-image. They're *not* installable from source, at least not the way pip expects (which I think should count as the standard), and that is breaking us because they're not producing Sierra wheels.
